# Generated by Django 3.1.7 on 2021-05-08 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Имя пользователя')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='ID пользователя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='telegrams', to='bot_user.botuser', verbose_name='Пользователь бота')),
            ],
            options={
                'verbose_name': 'Telegram',
                'verbose_name_plural': 'Telegram',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e164', models.CharField(max_length=50, verbose_name='Формат Е164')),
                ('international', models.CharField(editable=False, max_length=50, verbose_name='Интернациональный формат')),
                ('local_format', models.CharField(editable=False, max_length=50, verbose_name='Локальный формат')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bot_user.botuser', verbose_name='Пользователь бота')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
        ),
    ]
