# Generated by Django 3.1.7 on 2021-05-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='raw_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Сырой номер'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='e164',
            field=models.CharField(editable=False, max_length=50, verbose_name='Формат E164'),
        ),
    ]
