# Generated by Django 3.1.7 on 2021-03-30 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование категории')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование задачи')),
                ('done', models.BooleanField(blank=True, default=None, null=True, verbose_name='Выполнено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks_planning.taskcategory', verbose_name='Категория')),
            ],
        ),
    ]
