# Generated by Django 3.1.7 on 2021-04-24 06:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_planning', '0002_auto_20210422_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.RemoveField(
            model_name='taskcategory',
            name='name',
        ),
        migrations.AddField(
            model_name='task',
            name='countable_value',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(10)], verbose_name='Исчисляемое значение'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_name',
            field=models.CharField(default='Задача', max_length=200, verbose_name='Наименование задачи'),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='category_name',
            field=models.CharField(default='Категория', max_length=50, verbose_name='Наименование категории'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='tasks_planning.taskcategory', verbose_name='Категория'),
        ),
    ]
