# Generated by Django 3.1.7 on 2021-05-18 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_user', '0002_auto_20210508_1703'),
        ('tasks_planning', '0003_auto_20210424_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bot_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='bot_user.botuser', verbose_name='Пользователь бота'),
        ),
    ]
