# Generated by Django 3.1.7 on 2021-05-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_planning', '0004_task_bot_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcategory',
            name='category_name',
            field=models.CharField(blank=True, default='Категория', max_length=50, verbose_name='Наименование категории'),
        ),
    ]
