# Generated by Django 3.1.7 on 2021-05-23 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_user', '0002_auto_20210508_1703'),
        ('tasks_planning', '0005_auto_20210520_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='bot_user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.RESTRICT, to='bot_user.botuser', verbose_name='Пользователь бота'),
        ),
    ]
