# Generated by Django 3.1.7 on 2021-05-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_planning', '0006_auto_20210523_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='countable_value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Исчисляемое значение'),
        ),
    ]
