# Generated by Django 3.1.7 on 2021-06-14 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
                ('yandex_city_code', models.CharField(max_length=100, verbose_name='Код города Яндекса')),
            ],
            options={
                'verbose_name': 'Название города',
                'verbose_name_plural': 'Названия городов',
            },
        ),
        migrations.CreateModel(
            name='StationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_type', models.CharField(max_length=50, verbose_name='Тип станции')),
            ],
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(max_length=100, verbose_name='Тип транспорта')),
            ],
            options={
                'verbose_name': 'Тип транспорта',
                'verbose_name_plural': 'Типы транспорта',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название станции')),
                ('station_code', models.CharField(max_length=100, verbose_name='Яндекс код станции')),
                ('longitude', models.DecimalField(decimal_places=27, max_digits=30)),
                ('latitude', models.DecimalField(decimal_places=27, max_digits=30)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='yandex_schedule.city', verbose_name='Город станции')),
                ('station_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='yandex_schedule.stationtype', verbose_name='Тип станции')),
                ('transport_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='yandex_schedule.transporttype', verbose_name='Тип транспорта')),
            ],
            options={
                'verbose_name': 'Станция',
                'verbose_name_plural': 'Станции',
            },
        ),
    ]
