# Generated by Django 3.1.7 on 2021-06-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stationtype',
            options={'verbose_name': 'Тип станции', 'verbose_name_plural': 'Типы станций'},
        ),
        migrations.AlterField(
            model_name='stationtype',
            name='station_type',
            field=models.CharField(max_length=50, unique=True, verbose_name='Тип станции'),
        ),
        migrations.AlterField(
            model_name='transporttype',
            name='transport_type',
            field=models.CharField(max_length=100, unique=True, verbose_name='Тип транспорта'),
        ),
    ]
