# Generated by Django 3.1.7 on 2021-07-08 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_schedule', '0002_auto_20210615_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='yandex_schedule.city', verbose_name='Город станции'),
        ),
    ]
