# Generated by Django 3.1.7 on 2021-07-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_schedule', '0003_auto_20210708_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=27, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=27, max_digits=30, null=True),
        ),
    ]
