# Generated by Django 3.1.7 on 2021-05-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
    ]
